### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by superh1k** [SEARCAPhil/document_management_system#9]
Error importing files to database. 
When importing dms.sql then login_db_instance_1.sql you get error:
 #1054 - Unknown column 'profile_age' in 'field list'

When importing login_db_instance_1.sql then dms.sql you get error:
#1068 - Multiple primary key defined

**Comment by baradhili** [comment]
which version mysql/mariadb are you running?
Also have you tied it by copy/pasting manually into an interactive mysql client session? I also bumped into these errors, but they didn't re-appear when doing it interactively.. (yes weird)

**Comment by jkga** [comment]
Will now close this issue. Users on premise authentication is not supported in the latest upgrade of DMS which means `login_db_instance_1.sql` is not needed anymore.Please see https://github.com/SEARCAPhil/archives/tree/develop

Related:  #10
